/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms/$roomId'
import { Route as BedsBedIdRouteImport } from './routes/beds/$bedId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminRoomsRoomIdRouteImport } from './routes/admin/rooms.$roomId'
import { Route as AdminBedsRoomIdRouteImport } from './routes/admin/beds/$roomId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const BedsBedIdRoute = BedsBedIdRouteImport.update({
  id: '/beds/$bedId',
  path: '/beds/$bedId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoomIdRoute = AdminRoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => AdminRoomsRoute,
} as any)
const AdminBedsRoomIdRoute = AdminBedsRoomIdRouteImport.update({
  id: '/beds/$roomId',
  path: '/beds/$roomId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/rooms': typeof AdminRoomsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/beds/$bedId': typeof BedsBedIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/admin/': typeof AdminIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/admin/beds/$roomId': typeof AdminBedsRoomIdRoute
  '/admin/rooms/$roomId': typeof AdminRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/rooms': typeof AdminRoomsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/beds/$bedId': typeof BedsBedIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/admin': typeof AdminIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/admin/beds/$roomId': typeof AdminBedsRoomIdRoute
  '/admin/rooms/$roomId': typeof AdminRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/rooms': typeof AdminRoomsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/beds/$bedId': typeof BedsBedIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/admin/': typeof AdminIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/admin/beds/$roomId': typeof AdminBedsRoomIdRoute
  '/admin/rooms/$roomId': typeof AdminRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/rooms'
    | '/admin/users'
    | '/beds/$bedId'
    | '/rooms/$roomId'
    | '/admin/'
    | '/rooms/'
    | '/admin/beds/$roomId'
    | '/admin/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/rooms'
    | '/admin/users'
    | '/beds/$bedId'
    | '/rooms/$roomId'
    | '/admin'
    | '/rooms'
    | '/admin/beds/$roomId'
    | '/admin/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/rooms'
    | '/admin/users'
    | '/beds/$bedId'
    | '/rooms/$roomId'
    | '/admin/'
    | '/rooms/'
    | '/admin/beds/$roomId'
    | '/admin/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  BedsBedIdRoute: typeof BedsBedIdRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beds/$bedId': {
      id: '/beds/$bedId'
      path: '/beds/$bedId'
      fullPath: '/beds/$bedId'
      preLoaderRoute: typeof BedsBedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms/$roomId': {
      id: '/admin/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/admin/rooms/$roomId'
      preLoaderRoute: typeof AdminRoomsRoomIdRouteImport
      parentRoute: typeof AdminRoomsRoute
    }
    '/admin/beds/$roomId': {
      id: '/admin/beds/$roomId'
      path: '/beds/$roomId'
      fullPath: '/admin/beds/$roomId'
      preLoaderRoute: typeof AdminBedsRoomIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRoomsRouteChildren {
  AdminRoomsRoomIdRoute: typeof AdminRoomsRoomIdRoute
}

const AdminRoomsRouteChildren: AdminRoomsRouteChildren = {
  AdminRoomsRoomIdRoute: AdminRoomsRoomIdRoute,
}

const AdminRoomsRouteWithChildren = AdminRoomsRoute._addFileChildren(
  AdminRoomsRouteChildren,
)

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminRoomsRoute: typeof AdminRoomsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBedsRoomIdRoute: typeof AdminBedsRoomIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminRoomsRoute: AdminRoomsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBedsRoomIdRoute: AdminBedsRoomIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  BedsBedIdRoute: BedsBedIdRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
